### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by edify42** [helm-unittest/helm-unittest#102]
Hey @lrills - are you still around?

I think this is a pretty useful helm plugin but I noticed you haven't been active on GitHub lately.

I hope everything is ok.

❤️

**Comment by quintush** [comment]
@edify42 , i had some time left, so started updating some small features. 
Since it's not merged into this repo, you can download a version from my forked repo: https://github.com/quintush/helm-unittest/releases

@lrills, please respond, we would love to help improving this plugin.

**Comment by kir4h** [comment]
I was wondering the same, I like the unit test approach for the charts but the last commit was 1 year ago. So either adding more maintainers to the project (like @quintush) or if you feel you don't want to be involved anymore we can just switch to his fork.

**Comment by dschaaff** [comment]
Rancher also has a fork that at least works with helm 3

**Comment by kir4h** [comment]
If rancher wants to take over that would be great since they might have a bigger muscle for it (that is assuming @lrills wants to abandon it, let´s see if there is a statement). 
@quintush also included support for Helm3 and I am already using some v0.1.8 feature, thanks for that!

One way or another, let´s hope of having a single point of code anytime soon!

**Comment by xordspar0** [comment]
@quintush, I would like to see your changes getting merged into the Rancher fork. Both your fork and the Rancher fork have useful features, and it would be good to work on them together in one place.

**Comment by funkypenguin** [comment]
Hey @quintush, I've been trying to install your version (until the question of who maintains this is resolved), but the helm install process is failing ATM:

```
shasum: standard input: no properly formatted SHA1 checksum lines found
```

Sorry to peg this onto this issue, but your forked repo doesn't support issues :(

<details>
  <summary>Full debug output</summary>

````bash
❯ helm plugin install https://github.com/quintush/helm-unittest
+ PROJECT_NAME=helm-unittest
+ PROJECT_GH=quintush/helm-unittest
+ PROJECT_CHECKSUM_FILE=helm-unittest-checksum.sha
+ : /Users/davidy/Library/helm/plugins/helm-unittest
+ type cygpath
+ [[ '' == \1 ]]
+ trap fail_trap EXIT
+ set -e
+ initArch
++ uname -m
+ ARCH=x86_64
+ case $ARCH in
+ ARCH=amd64
+ initOS
++ tr '[:upper:]' '[:lower:]'
+++ uname
++ echo Darwin
+ OS=darwin
+ case "$OS" in
+ OS=macos
+ verifySupported
+ local 'supported=linux-arm64\nlinux-amd64\nmacos-amd64\nwindows-amd64'
+ echo 'linux-arm64\nlinux-amd64\nmacos-amd64\nwindows-amd64'
+ grep -q macos-amd64
+ type curl
+ echo 'Support macos-amd64'
Support macos-amd64
+ getDownloadURL
+ local latest_url=https://api.github.com/repos/quintush/helm-unittest/releases/latest
+ [[ -z '' ]]
++ git describe --tags --exact-match
+ local version=
+ '[' -n '' ']'
+ echo 'Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/latest'
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/latest
+ type curl
++ curl -s https://api.github.com/repos/quintush/helm-unittest/releases/latest
++ grep 'macos\(-amd64\)\?'
++ awk '/\"browser_download_url\":/{gsub( /[,\"]/,"", $2); print $2}'
+ DOWNLOAD_URL=https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-macos-amd64-0.2.0.tgz
++ curl -s https://api.github.com/repos/quintush/helm-unittest/releases/latest
++ grep checksum
++ awk '/\"browser_download_url\":/{gsub( /[,\"]/,"", $2); print $2}'
+ PROJECT_CHECKSUM=https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-checksum.sha
+ downloadFile
+ PLUGIN_TMP_FOLDER=/tmp/_dist/
+ mkdir -p /tmp/_dist/
+ echo 'Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-macos-amd64-0.2.0.tgz to location /tmp/_dist/'
Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-macos-amd64-0.2.0.tgz to location /tmp/_dist/
+ type curl
+ cd /tmp/_dist/
+ curl -LO https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-macos-amd64-0.2.0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   648  100   648    0     0   1325      0 --:--:-- --:--:-- --:--:--  1325
100 16.7M  100 16.7M    0     0  3923k      0  0:00:04  0:00:04 --:--:-- 4795k
+ installFile
+ cd /tmp
++ find ./_dist -name '*.tgz'
+ DOWNLOAD_FILE=./_dist/helm-unittest-macos-amd64-0.2.0.tgz
+ '[' -n https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-checksum.sha ']'
+ echo Validating Checksum.
Validating Checksum.
+ type curl
+ curl -s -L https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-checksum.sha
+ grep ./_dist/helm-unittest-macos-amd64-0.2.0.tgz
+ shasum -a 256 -c -s
shasum: standard input: no properly formatted SHA1 checksum lines found
+ fail_trap
+ result=1
+ '[' 1 '!=' 0 ']'
+ echo 'Failed to install helm-unittest'
Failed to install helm-unittest
+ echo 'For support, go to https://github.com/kubernetes/helm'
For support, go to https://github.com/kubernetes/helm
+ exit 1
Error: plugin install hook for "unittest" exited with error
````

</details>

**Comment by jgoeres** [comment]
I would also love to see this project continued - once a Helm chart reaches a certain complexity, it becomes really difficult to maintain without some serious unit testing. We will give the forks mentioned above a try.

**Comment by gmariotti** [comment]
Hey @quintush, what about trying to have your fork submitted to the helm project? I saw that there is an issue already open for it https://github.com/helm/helm/issues/5424

**Comment by mik-laj** [comment]
Hello,

In the Apache Airflow project, we made the decision to migrate to Python tests supported by a small function that is used to generate templates. I think this could also be a solution to this problem. Tests written in Python will be easier to maintain than using a specific framework.

I described the details in the ticket: https://github.com/lrills/helm-unittest/issues/110

Best regards,
Kamil Breguła

**Comment by lrills** [comment]
Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.

@quintush thanks for the works. If you are willing to continue maintaining, I can transfer the repository ownership. So it'll not show _forked from_ to the archived upstream.

**Comment by quintush** [comment]
> Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
> 
> @quintush thanks for the works. If you are willing to continue maintaining, I can transfer the repository ownership. So it'll not show _forked from_ to the archived upstream.

Hello @lrills,

If it is not a big problem, please transfer the repository ownership.

Greetings,
@quintush

**Comment by lrills** [comment]
@quintush I can't transfer directly because of the fork. I've moved repo to an organization and invite you as owner. Feel free to merge and transfer repo to your own account.
Thanks!

**Comment by Romain-Geissler-1A** [comment]
Hi,

What is the status of helm unittest ? I can see @quintush and also the rancher fork https://github.com/rancher/helm-unittest where someone tried to integrate changes from @quintush in a never merged pull request. Among these two forks, who claims to be the "official" new real helm-unittest repository ? It seems both have diverged.

Cheers,
Romain

**Comment by quintush** [comment]
Hello @Romain-Geissler-1A ,

I planning to have a 0.3.0 version build and pushed as the 'official' helm unittest.
The 0.3.0 will include the following:
- Move to this repository to be the single truth, universal naming and more flexible to add additional maintainers.
- Removed helm 2 support (less code to maintain) (breaking change)
- Support for JSONPath (breaking change)
- Previous featureset
- Updated packages

**Comment by Romain-Geissler-1A** [comment]
Ok thanks for the info.

I will wait fo this new official 0.3.0 to happen then. I know in the "new" cloud ecosystem people have no problem to include some personal repositories in their corporate dependances, but I don't want to do this. So I will wait for a more "official" release instead of using your fork for now.

**Comment by quintush** [comment]
Finally created a new release with new advanced features and more to come 

Greetings,
@quintush
