### ISSUE TITLE
Partial templates defined in a subchart of a subchart are not added automatically

### ISSUE THREAD

**Issue by wirtsi** [helm-unittest/helm-unittest#123]
Alright, here is a weird one

I have a chart that uses a template from a subchart of a subchart. That means, my chart has
```dependencies:
  - name: http-app
    version: 1.6.1
    repository: "@zhelm"
```
`http-app` itself has a dependency `common`, which includes some basic templates that I am using, so eg.
`name: {{ include "common.fullname" . }}`

This setup works fine when rendering the chart, but when running a unittest I get this error

> Error: template: shop-http-app/templates/routetable_v2.yaml:2:4: executing "shop-http-app/templates/routetable_v2.yaml" at <include "shop-http-app.routeTable_v2" (list . "mychart.routeTable_v2")>: error calling include: template: shop-http-app/templates/_route_table_v2.tpl:56:13: executing "shop-http-app.routeTable_v2" at <{{template "common.util.merge" (append . "shop-http-app.routeTable_v2.tpl")}}>: template "common.util.merge" not defined

I found out how I can fix it. In my charts `charts` folder, I untar the http-app.1.6.1.tgz file, which gives me this structure

> .
> └── http-app
>     ├── charts
>     │   └── common
>     │       └── templates (A)
>     └── templates (B)

It should be noted that (A) only holds partial templates (eg. _common.tpl)

If I copy the files from (A) into (B), the tests are working.

So my guess would be the the globbing for finding partial templates is not doing the right thing

Bests & thnx wirtsi

**Comment by quintush** [comment]
Hello @wirtsi,

Thanks for the feedback.

It seems a similar situation like the test [with-subsubcharts](https://github.com/helm-unittest/helm-unittest/tree/main/test/data/v3/with-subsubcharts) only with library charts.
The code was expected to always load partial templates, so it should automatically work with library charts.
However it seems here is some validation missing.

Will setup additional validation wich also include library charts to validate the library charts behaviour.

Greetings,
@quintush

**Comment by wirtsi** [comment]
Hey @quintush, thanks for looking into this

**Comment by quintush** [comment]
Hello @wirtsi,

Do you run a helm dependency update <chart> before running the helm unittest <chart>?
Currently the helm unittest is expecting a filled charts folder. It is not able to download all it's dependencies before running the unittests.

If you do have all dependencies in the chart folder, can you please send me an example of the tests.yaml, to check wheter specific templates are being tested.

Greetings,
@quintush

**Comment by wirtsi** [comment]
Ah dang, I figured this out. It is a problem somewhat on my side, but it's still wild

So:
* Inside the http-app chart file, the common chart is referenced with file://../common (because both live in the same repo originally)
* When using the http-app as a subchart for my shop-http-app chart, the `..` path actually becomes incorrect because the common library sits in http-app's chart directory, not one level up

When I untar the http-app-1.6.tgz file and change the path to read file://charts/common, the tests work

It still be noted that the actual rendering of it works perfectly fine, no idea how the resolution works in this case

FYI, this is the directory structure created when running `helm dependency update``

```
.
├── charts
│   └── http-app
│       ├── charts
│       │   └── common
│       │       └── templates
│       └── templates
```

>
