### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by aroberts87** [helm-unittest/helm-unittest#130]
I am unable to install the plugin using the provided command in the README.
```
>? helm plugin install https://github.com/helm-unittest/helm-unittest
Error: Unable to update repository: exit status 1
```

This does not seem to be resolved by trying older versions either.
```
>? helm plugin install https://github.com/helm-unittest/helm-unittest --version=0.2.11
Error: Unable to update repository: exit status 1
>? helm plugin install https://github.com/helm-unittest/helm-unittest --version=0.1.5
Error: Unable to update repository: exit status 1
```

**Comment by quintush** [comment]
Hello @aroberts87,

The installation should be fixed. 
Somehow the installation is mixed with the old forked release.

In case the error still occurs, clean the helm cache[Helm cache](https://helm.sh/docs/helm/helm/) before retrying 

Greetings,
@quintush

**Comment by aroberts87** [comment]
Thank you so much, @quintush! Much appreciated! 🙏🏻
