### ISSUE TITLE
failedTemplate assertion does not work properly

### ISSUE THREAD

**Issue by LukasVyhlidkaS1** [helm-unittest/helm-unittest#133]
Hello,

when upgraded to latest version `0.3.1` I experienced a lot of failed tests that use `failedTemplate` assertion.

After some investigation I extended `test/data/v3/basic` tests to show the problem in the fork repo - https://github.com/helm-unittest/helm-unittest/compare/main...LukasVyhlidkaS1:helm-unittest:main

The issue arises when the failure occurs in multiple templates, even though the test itself depends only on one of templates.

In the fork, the failing test suite is in [deployment_test.yaml](https://github.com/helm-unittest/helm-unittest/compare/main...LukasVyhlidkaS1:helm-unittest:main#diff-0a37ff51ea2d3c66140fa6f6b61d69b64c81752e4e371636f7126873d9902a12) file and named `should fail if env is not present`.
 
It tests only the [deployment.yaml](https://github.com/helm-unittest/helm-unittest/compare/main...LukasVyhlidkaS1:helm-unittest:main#diff-d4dea064d8b9a2f1e7e81dc0dedcfaa80cc30c813af08dc1689217b7eb3de4db) template by setting the `env` property to null.

But because the failure occurs even in [env-helper.yaml](https://github.com/helm-unittest/helm-unittest/compare/main...LukasVyhlidkaS1:helm-unittest:main#diff-3913e7b0f264e2954dc2b38b5d1eefd922efb13d3198d188b9732e33dff0aa27) template, the assertion fails.

The opposite direction (the equal test from the other side - [env-helper_test.yaml](https://github.com/helm-unittest/helm-unittest/compare/main...LukasVyhlidkaS1:helm-unittest:main#diff-88ac407ca930ccc70d77495096956e9895c3274c332ceadeb072d2c4f862bfef)) works fine which suggests that the ordering plays some role.

The previous version 0.3.0 worked fine. Here is the command line output when I run unittests with version 0.3.0, then upgrade to 0.3.1 and run it again:

``` bash
➜  basic git:(main) ✗ helm plugin list
NAME       	VERSION	DESCRIPTION
mapkubeapis	0.4.1  	Map release deprecated Kubernetes APIs in-place
unittest   	0.3.0  	Unit test for helm chart in YAML with ease to keep your chart functional and robust.


➜  basic git:(main) ✗ helm unittest .

### Chart [ basic ] .

 PASS  Configmap multiline Test	tests/configmap_test.yaml
 PASS  Custom Resource Definition Test	tests/crd_test.yaml
 PASS  test deployment	tests/deployment_test.yaml
 PASS  test env-helper	tests/env-helper_test.yaml
 PASS  test ingress	tests/ingress_test.yaml
 PASS  test notes	tests/notes_test.yaml
 PASS  test service	tests/service_test.yaml

Charts:      1 passed, 1 total
Test Suites: 7 passed, 7 total
Tests:       20 passed, 20 total
Snapshot:    4 passed, 4 total
Time:        30.304583ms


➜  basic git:(main) ✗ helm plugin update unittest
Support macos-arm64
Retrieving https://api.github.com/repos/helm-unittest/helm-unittest/releases/latest
Downloading https://github.com/helm-unittest/helm-unittest/releases/download/v0.3.1/helm-unittest-macos-arm64-0.3.1.tgz to location /tmp/_dist/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.4M  100 19.4M    0     0  4615k      0  0:00:04  0:00:04 --:--:-- 6009k
...
... (shortened)
...
Updated plugin: unittest


➜  basic git:(main) ✗ helm unittest .

### Chart [ basic ] .

 PASS  Configmap multiline Test	tests/configmap_test.yaml
 PASS  Custom Resource Definition Test	tests/crd_test.yaml
 FAIL  test deployment	tests/deployment_test.yaml
	- should fail if env is not present

		- asserts[0] `failedTemplate` fail
			Template:	basic/templates/deployment.yaml

 PASS  test env-helper	tests/env-helper_test.yaml
 PASS  test ingress	tests/ingress_test.yaml
 PASS  test notes	tests/notes_test.yaml
 PASS  test service	tests/service_test.yaml

Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 6 passed, 7 total
Tests:       1 failed, 19 passed, 20 total
Snapshot:    4 passed, 4 total
Time:        34.625167ms

Error: plugin "unittest" exited with error
```

**Comment by quintush** [comment]
Hello @LukasVyhlidkaS1,

Thanks for the feedback.
I will add the scenarios as part of the tests and validate why the result is different than previous.

Greetings,
@quintush

**Comment by quintush** [comment]
Hello @LukasVyhlidkaS1,

I have checked the situation. The rootcause is not related to the failedTemplate, but to the order of the rendered sources.
The order is not consistent, which result in false positives.

Will work on it, but it will not be fixed quickly.

Greetings,
@quintush

**Comment by LukasVyhlidkaS1** [comment]
Hello @quintush,

thank you for the investigation and help.

In my test scenario, there are two tests that catches the error based on the same missing data. From what you said I understand that one test (e.g. test A) is failing while the other (e.g. test B) is OK because of the ordering. But if we change the order, won't the result be just that the test B fails and test A is OK (the opposite)?

Is there any relevant part in the code to share?
