### ISSUE TITLE
Feature request: equal/matchRegex testing for secret data

### ISSUE THREAD

**Issue by TheMeier** [helm-unittest/helm-unittest#136]
Would it be possible to have something like a `matchRegexB64` assertion which does a base64-decode on the field value before doing a regxex check. The use case for this is testing data inside secrets which have been generated programmatically.

**Comment by quintush** [comment]
Hello @TheMeier,

Added an option to the existing assertions, instead of creating new assertions.

Greetings,
@quintush

**Comment by TheMeier** [comment]
Hi @quintush 

Thats really great, thanks a lot
