### ISSUE TITLE
helm-unittest/helm-unittest is not up-to-date

### ISSUE THREAD

**Issue by mloiseleur** [helm-unittest/helm-unittest#137]
Following #122, the script is updated but it seems it's not called or working as expected. 

I notice that latest release on docker hub is [still 0.3.0](https://hub.docker.com/r/quintush/helm-unittest/tags), published a month ago.
And so is the [docker usage](https://github.com/helm-unittest/helm-unittest#docker-usage) part of readme.

Would you please update it with v0.3.1 ?

**Comment by quintush** [comment]
Hello @mloiseleur,

Please try the new location on dockerhub:

https://hub.docker.com/r/helmunittest/helm-unittest

The move to a new docker location is done after the first update of 0.3.0 is created.

Greetings,
@quintush

**Comment by mloiseleur** [comment]
Ah yes, it seems better. 
Thanks !
