### ISSUE TITLE
Feature request: assert comparison operations between two rendered templates

### ISSUE THREAD

**Issue by sbhrule15** [helm-unittest/helm-unittest#142]
If this is already integrated into this, please let me know!

I would love to be able to have unit tests to make sure that the values between two different templates match. For example, I would love to assert that the matchLabels in my service.yaml matches the labels in my deployment.yaml, or my service account name matches the name in the service account. I currently don't see a way to reference a template inside of an assertion match.

Would this be out of scope for this project, where it wouldn't be considered something a unit test shouldn't do, or is this a valid feature request? Thanks!

**Comment by quintush** [comment]
Hello @sbhrule15,

The feature is already available.
It documented to setup a list of templates to validate, but created an example (https://github.com/helm-unittest/helm-unittest/blob/feature/ExampleValidationMultipleResources/test/data/v3/basic/tests/namesOverride_test.yaml) to help.

Greetings,
@quintush
