### ISSUE TITLE
Wildcard renders templates with inconsistent order

### ISSUE THREAD

**Issue by rperryng** [helm-unittest/helm-unittest#149]
I'm interested in writing a snapshot test that uses all the templates of my chart.  Rather than listing out each template to ensure it's included in the snapshot, I wanted to use a wildcard to simply match all templates.  This way, new templates are automatically added to the snapshot without having to remember to add it to the `templates` list.

```yaml
suite: Full Snapshot
templates:
  - '*.yaml'
tests:
  - it: matches the snapshot
    asserts:
      - matchSnapshot: {}
```

However, the rendered result doesn't seem to maintain a consistent order, so generating the snapshot multiple times can result in a different snapshot each time.

If I hard-code the template names then the snapshot does seem to maintain consistent order.

I prepared an example repository that reproduces the problem [here](https://github.com/rperryng/helm-unittest-demo/tree/1564dcda3eed9a5e36727b6c93da857232045770).  I created the repo using `helm create demo` and added a snapshot test with the wildcard.

Other information:
```
❯ helm version
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}

❯ helm plugin list                     
NAME            VERSION DESCRIPTION                                                                         
unittest        0.3.2   Unit test for helm chart in YAML with ease to keep your chart functional and robust.
```

**Comment by quintush** [comment]
Hello @rperryng,

I'm aware of the ordering. Have several issues with it and I'm working on to force a predictable order, see #133 as an example where ordering is also conflicting the behaviour.

Greetings,
@quintush

**Comment by rperryng** [comment]
Ahh thanks for the pointer!  And sorry for the noise - I did try to see if this issue had already been raised but clearly not closely enough :)

I will close this issue and follow the linked.

Thanks for all your support.
