### ISSUE TITLE
Feature request:  suite-level set block

### ISSUE THREAD

**Issue by jcogilvie** [helm-unittest/helm-unittest#155]
Use case:  my chart has several values which are required to render (using the helm `required` function).  They are often not related to the unit under test.

I would like to see a `set` block at the suite level, which applies the values to all tests in the suite and treats `set` blocks at the test level as overrides in case of a conflict.

**Comment by maverick1872** [comment]
I second this myself.

**Comment by jcogilvie** [comment]
I think I'd really like visibility into these values at the suite level, rather than storing configuration across multiple files, so if it's not too much trouble I'd still like to see a suite-level `set` block with the same syntax as the test-level block.
