### ISSUE TITLE
is helm chart validation.tpl logic supported?

### ISSUE THREAD

**Issue by ivankatliarchuk** [helm-unittest/helm-unittest#158]
I've created a [demo repository](https://github.com/ik-workshop/helmunittest-validator).

Context

`failedTemplate` only supported for failures within a temlplate. Not clear how to run tests when there is chart global validation logic.

Structure
```
├── example-chart
│   ├── Chart.yaml
│   ├── templates
│   │   ├── configMap.yaml
│   │   └── validation.tpl
│   ├── tests
│   │   └── configMap_test.yaml
│   └── values.yaml
```

Helm test is based off https://github.com/ik-workshop/helmunittest-validator/tree/master/example-chart/tests

When running `the helm template` the validation error is correct
```
Error: ........ The `.Release.name` must be <= 3 characters!
```

When executing  `helm unittest -f 'tests/*.yaml' example-chart`

```
helm unittest -f 'tests/*.yaml' example-chart

### Chart [ failing-template ] example-chart

 FAIL  Test failing template	example-chart/tests/configMap_test.yaml
	- template should be failing

		- asserts[0] `failedTemplate` fail
			Template:	failing-template/templates/configMap.yaml

		- asserts[1] `failedTemplate` fail
			Template:	failing-template/templates/configMap.yaml


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        2.846286ms

Error: plugin "unittest" exited with error
make: *** [unit-test-local] Error 1
``` 

Debug does not help much.

Any example how to assert `validar.tpl` failures?

Example validation

```
{{/* Checks for `.Release.name` */}}
{{- if gt (len .Release.Name) 3 }}
  {{ required "The `.Release.name` must be <= 3 characters!" .Values.versionAlwaysFail }}
{{- end }}
```

**Comment by quintush** [comment]
Hello @ivankatliarchuk,

I have updated the loading of files with tpl and yml extension to support the same behavior as the helm template.

Be aware that loading a failed template only result in a single failed template message.

I have expanded the [failing-template chart](https://github.com/helm-unittest/helm-unittest/tree/main/test%2Fdata%2Fv3%2Ffailing-template) to show the possibilities of validating failed templates, including the validation.tpl.

Greetings,
@quintush
