### ISSUE TITLE
Assert fail

### ISSUE THREAD

**Issue by hurtadosanti** [helm-unittest/helm-unittest#163]
Is it possible to assert that setting a value a fail("") is raised?

**Comment by quintush** [comment]
Hello @hurtadosanti,

The option is already available with the [failedTemplate](https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#assertion-types) assertion.

When fail("") is triggered in a helm chart, it results in a failing template.

greetings,
@quintush

**Comment by quintush** [comment]
Closed as question is answered.

**Comment by Dzeri96** [comment]
Hi @quintush, I was just trying to test this case and what you're saying doesn't seem to work.
If I use `failedTemplate`, the error I get is:
```
- asserts[0] `failedTemplate` fail
                        Template:       use-endpoint/templates/spark/configmap-pod-template.yaml
                        Expected to match:
                                .*
                        Actual:
                                No failed document
```
If I remove it and use `hasDocuments`, the test fails with the message raised by `fail`. Should I open a bug ticket?

**Comment by quintush** [comment]
> Hi @quintush, I was just trying to test this case and what you're saying doesn't seem to work.
> If I use `failedTemplate`, the error I get is:
> ```
> - asserts[0] `failedTemplate` fail
>                         Template:       use-endpoint/templates/spark/configmap-pod-template.yaml
>                         Expected to match:
>                                 .*
>                         Actual:
>                                 No failed document
> ```
> If I remove it and use `hasDocuments`, the test fails with the message raised by `fail`. Should I open a bug ticket?

Hello @Dzeri96 

Please create a bug ticket and if possible send the template to be tested and the test with it. So I can validate what is happening.

Greetings,
@quintush
