### ISSUE TITLE
Glob path works strange

### ISSUE THREAD

**Issue by pmoscode** [helm-unittest/helm-unittest#175]
Hi folks,

I have an issue with unit tests when I run the tests with:

`helm unittest -f tests/**/*_test.yaml`

My folder structure looks like this (I want to put the yaml files in a separate folder for each configuration aka default, test, dev, prod, ...):

<img width="269" alt="image" src="https://github.com/helm-unittest/helm-unittest/assets/56410761/c20ddb62-9445-41b2-ba64-6635cacd5c49">

So, when I execute it, I got this:

> task: [unittest] helm unittest -f tests/**/*_test.yaml .
> 
> ### Error:  file 'tests/default/service_account_test.yaml' seems to be a YAML file, but expected a gzipped archive
> 
> 
> ### Error:  file 'tests/default/service_test.yaml' seems to be a YAML file, but expected a gzipped archive
> 
> 
> ### Chart [ bla bla ] .
> 
>  PASS  test default deployment  tests/default/deployment_test.yaml
> 
> Charts:      2 failed, 2 errored, 1 passed, 3 total
> Test Suites: 1 passed, 1 total
> Tests:       5 passed, 5 total
> Snapshot:    0 passed, 0 total
> Time:        113.48075ms
> 
> Error: plugin "unittest" exited with error
> task: Failed to run task "unittest": exit status 1
> task: Failed to run task "unittest": exit status 1

It seems that the glob pattern is faulty. How can I fix that? Or is that a GO behavior?

Thx

**Comment by pmoscode** [comment]
I have solved the issue by myself.
It's important to surround the path with quotes...

Now it's working.

**Comment by swathinsankaran** [comment]
@pmoscode could you please give an example? I am facing the same issue.

**Comment by pmoscode** [comment]
@swathinsankaran 
Sure, for me worked: ` helm unittest -f 'tests/**/*.yaml' .`

Like I mentioned above, I used single quotes around the path to get it working.

**Comment by swathinsankaran** [comment]
Thanks @pmoscode for the reply.

I ended up adding the below docker command to solve the issue.
```
helmtests:
	sudo docker run \
	-v $(PWD)/helm/ako:/apps \
	-v $(PWD)/tests/helmtests:/apps/tests \
	helmunittest/helm-unittest:3.11.1-0.3.0 .
```

**Comment by pmoscode** [comment]
Perhaps it's worth to mention, that my I'm using a Mac for development. So, perhaps my solution isn't working on other operating systems... I didn't check.

**Comment by quintush** [comment]
Hello @swathinsankaran,

Based on your docker command it seems you are retrieving the test from a folder which is not part of the helmchart itself.
Although the glob path can work like that, the current implementation starts the globbing with the helmchart as basepath.

It seems you are looking for a feature similar to #186.

Greetings,
@quintush
