### ISSUE TITLE
Checksum invalid option when installing in Alpine

### ISSUE THREAD

**Issue by cattapan** [helm-unittest/helm-unittest#176]
This line has a bug:
https://github.com/helm-unittest/helm-unittest/blob/fb66fab3001965a237e045398a8658a76032c344/install-binary.sh#L124

In alpine, sha256sum has no "-s" option.

![Screenshot 2023-06-27 at 16 09 33](https://github.com/helm-unittest/helm-unittest/assets/33495835/b6ba53fa-49b5-4108-b8de-9b7b061c69e7)

**Comment by quintush** [comment]
Hello @cattapan,

Can you tell me which version of sha256sum you are using.
The alpine version I'm using for testing all contain the -s option.

![image](https://github.com/helm-unittest/helm-unittest/assets/2246480/d66f2d56-687a-4b66-a3dd-a0511912cfa6)

Greetings,
@quintush

**Comment by cattapan** [comment]
Right. that's an interesting one. we are using it from coreutils. That does not have -s option...

<img width="900" alt="Screenshot 2023-07-30 at 13 30 57" src="https://github.com/helm-unittest/helm-unittest/assets/33495835/585fdbb9-7d7d-4a7d-a085-671f90ee838e">
