### ISSUE TITLE
`untt: no such file or directory` error

### ISSUE THREAD

**Issue by nitrocode** [helm-unittest/helm-unittest#177]
Hi. Thank you for all the work you folks are doing here. I'm excited to learn this method of unit testing helm charts. I'm hitting an issue right in the beginning.

I'm on an arm architecture

```
✗ helm version
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

I ran

```
helm plugin install https://github.com/helm-unittest/helm-unittest.git
```

I get this error

```
✗ helm unittest .
Error: fork/exec /Users/<snip>/Library/helm/plugins/helm-unittest.git/untt: no such file or directory
```

I looked at a previous issue https://github.com/helm-unittest/helm-unittest/issues/87 and it said to use @quintush 's fork which now seems to be this repo again ? Unsure on what to do here.

---

Found this workaround https://github.com/helm-unittest/helm-unittest/issues/87#issuecomment-600520340

```
wget https://github.com/helm-unittest/helm-unittest/releases/download/v0.3.3/helm-unittest-macos-arm64-0.3.3.tgz
tar xzf  helm-unittest-macos-arm64-0.3.3.tgz -C $HOME/Library/helm/plugins/helm-unittest.git/
rm helm-unittest-macos-arm64-0.3.3.tgz
```

Now it works!

```
helm unittest .
```

**Comment by mohamedragab2024** [comment]
You can go `/Users/<snip>/Library/helm/plugins/helm-unittest.git` and run
`make build`
