### ISSUE TITLE
Unauthenticated GitHub API usage during instal

### ISSUE THREAD

**Issue by raxod502-plaid** [helm-unittest/helm-unittest#181]
The [`install-binary.sh`](https://github.com/helm-unittest/helm-unittest/blob/main/install-binary.sh) script makes a request to `api.github.com` without authentication during `helm plugin install`. While this is reasonable, unfortunately the GitHub API has intense rate limits for unauthenticated usage. In our environment, all of our CI runners appear under the same set of IP addresses because they all pass through a NAT gateway to the public internet, which means `helm plugin install` is often failing since we added helm-unittest to our build.

Since using the GitHub API is not actually required to get the download URL when a version is specified, what about skipping that except when no version is given? Or alternatively, allowing the use of `GITHUB_TOKEN` from the environment if present?

**Comment by quintush** [comment]
Hello @raxod502-plaid,

Thanks for the feedback.
Based on your PR the download url can be retrieved faster without additional requests.

I have created a new PR (#190) which still supports the checksum validation and allows to install the plugin using the local installer.

Greetings,
@quintush
