### ISSUE TITLE
Cannot test sub-sub chart correctly

### ISSUE THREAD

**Issue by zidoshare** [helm-unittest/helm-unittest#206]
<img width="1603" alt="image" src="https://github.com/helm-unittest/helm-unittest/assets/11310504/e777bf45-66dd-4eb4-bb10-2def399ce87a">
<img width="1155" alt="image" src="https://github.com/helm-unittest/helm-unittest/assets/11310504/6f285fb6-7a75-4b12-9f5c-a351ccefe2b1">

I try to add a test case in the nested subchart, and run unittest in the outermost chart, the final result is `template "with-subsubcharts/charts/example-subchart/charts/example-sub-subchart /templates/deployment.yaml" not exists or not selected in test suite`.

**Comment by zidoshare** [comment]
#207

**Comment by quintush** [comment]
Hello @zidoshare,

Thanks for the improvement.
Will look at the PR.

Greetings,
@quintush
