### ISSUE TITLE
helm plugin install https://github.com/helm-unittest/helm-unittest.git doesn't install latest version

### ISSUE THREAD

**Issue by csun-cpointe** [helm-unittest/helm-unittest#214]
It seems the  `helm plugin install https://github.com/helm-unittest/helm-unittest.git` doesn't install latest version as expected or it might be something that I missed..

When I install helm plugin unittest with version 0.3.3, the version 0.3.3 will be installed correctly and then I uninstall the plugin and install again using the `helm plugin install https://github.com/helm-unittest/helm-unittest.git` command, it will reinstall the v0.3.3 again instead of the latest version v0.3.5

 % **helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.3.3**
Support macos-arm64
Retrieving https://api.github.com/repos/helm-unittest/helm-unittest/releases/tags/v0.3.3
Downloading https://github.com/helm-unittest/helm-unittest/releases/download/v0.3.3/helm-unittest-macos-arm64-0.3.3.tgz to location /tmp/_dist/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.5M  100 19.5M    0     0  11.7M      0  0:00:01  0:00:01 --:--:-- 16.4M
Validating Checksum.
Preparing to install into /Users/usera/Library/helm/plugins/helm-unittest.git
helm-unittest installed into /Users/usera/Library/helm/plugins/helm-unittest.git
Running chart unittest written in YAML.
................................... (omitted)
Installed plugin: unittest
 % **helm plugin uninstall unittest**                                                        
Uninstalled plugin: unittest
 % **helm plugin install https://github.com/helm-unittest/helm-unittest.git**                
Support macos-arm64
Retrieving https://api.github.com/repos/helm-unittest/helm-unittest/releases/tags/v0.3.3
Downloading https://github.com/helm-unittest/helm-unittest/releases/download/v0.3.3/helm-unittest-macos-arm64-0.3.3.tgz to location /tmp/_dist/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.5M  100 19.5M    0     0  11.6M      0  0:00:01  0:00:01 --:--:-- 16.1M
...................................(omitted)
Installed plugin: unittest
 %

**Comment by quintush** [comment]
Hello @csun-cpointe,

The behaviour seems related to the caching of the plugin by helm. Will check if there is a way to control the cache.

Can you validate if the update does update the plugin to the latest version?

Using: helm plugin update unittest

Greetings,
@quintush

**Comment by csun-cpointe** [comment]
@quintush thanks for the reply.
it gives an error when I run the command
```
 % helm plugin update unittest
Error: Plugin: unittest not found
```

**Comment by csun-cpointe** [comment]
@quintush I realized that the error I had is because I removed cache but I am still having issues if I don't remove cache and just use the `helm plugin update unittest` (updated above comment with correct error)

**Comment by quintush** [comment]
Hello @csun-cpointe,

Thanks for the update.
Will check if the installation can be simplified.

Greetings,
@quintush
