### ISSUE TITLE
Unable to download and install older version of the plugin (But the files are still there?)

### ISSUE THREAD

**Issue by LucasWiman113** [helm-unittest/helm-unittest#225]
Hello

I am trying to download and install an older version of the plugin, but I am getting some odd behaviour

`*seroiuts02335(UnitTestAdjust)> helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.3.1 --debug                                                                                       # /workspace/git/elucwim/epg
[debug] vcs_installer.go:162: updating https://github.com/helm-unittest/helm-unittest.git
[debug] vcs_installer.go:131: found refs: [v0.1.0 v0.1.1 v0.1.2 v0.1.3 v0.1.4 v0.1.5 v0.1.6 v0.1.7 v0.1.8 v0.2.0 v0.2.1 v0.2.10 v0.2.11 v0.2.2 v0.2.3 v0.2.4 v0.2.5 v0.2.6 v0.2.7 v0.2.8 v0.2.9 v0.3.0 v0.3.1 v0.3.2 v0.3.3 v0.3.4 v0.3.5]
[debug] vcs_installer.go:142: setting to v0.3.1
[debug] vcs_installer.go:152: setting version to "0.3.1"
[debug] vcs_installer.go:91: copying /home/elucwim/.cache/helm/plugins/https-github.com-helm-unittest-helm-unittest.git to /home/elucwim/.local/share/helm/plugins/helm-unittest.git
plugin_install.go:82: [debug] loading plugin from /home/elucwim/.local/share/helm/plugins/helm-unittest.git
plugin.go:60: [debug] running install hook: /bin/sh -c cd $HELM_PLUGIN_DIR; ./install-binary.sh
Support linux-amd64
Retrieving https://api.github.com/repos/helm-unittest/helm-unittest/releases/tags/v0.3.1
No download_url found only searching for linux
Downloading  to location /tmp/_dist/
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
helm.go:88: [debug] plugin install hook for "unittest" exited with error
main.runHook
	helm.sh/helm/v3/cmd/helm/plugin.go:67
main.(*pluginInstallOptions).run
	helm.sh/helm/v3/cmd/helm/plugin_install.go:88
main.newPluginInstallCmd.func3
	helm.sh/helm/v3/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371`

But despite this, the files still appear in my folder, with the correct version aswell. But I cant run helm unit tests of course.

![Screenshot from 2023-10-02 11-39-52](https://github.com/helm-unittest/helm-unittest/assets/5427697/d2dff4e0-17b2-4a7d-a29e-7f56662dbee5)

`Error: fork/exec /home/elucwim/.local/share/helm/plugins/helm-unittest.git/untt: no such file or directory`

This does not happen with the latest version 0.3.5 though. I can download and install that one just fine. But I am wondering if this is intentional? Shouldnt it be possible to download whichever version you want?

Best regards,
Lucas

**Comment by quintush** [comment]
Hello @LucasWiman113,

When cleaning the temp and cache folder manually (see https://github.com/helm-unittest/helm-unittest/blob/main/FAQ.md#installation) you could install the older version.
Because of caching the old version keeps popping up.
With an optimization of the install script (#214) I hope to have a more stable rerun.

Greetings,
@quintush
