### ISSUE TITLE
Follow semver for release

### ISSUE THREAD

**Issue by gionn** [helm-unittest/helm-unittest#236]
Hello, reading the release notes of each release looks like this project is not properly following semver.

e.g. https://github.com/helm-unittest/helm-unittest/releases/tag/v0.3.6
has new features and improvements, should have been released as v.0.4.0

Following semver really help in making people aware of the kind of changes and help in building update automations around that.

**Comment by quintush** [comment]
Hello @gionn,

The intent is to follow semver for release, although I'm not in favor of having each new feature as a minor release.
Features that are still under development or are not fully validated by the goal I would like to achieve are for me still part of a patch release.
I do check the existing behaviour does not change, based on the new 'partial' feature.
 
Greetings,
@quintush
