### ISSUE TITLE
trim copying in v0.3.6

### ISSUE THREAD

**Issue by carloscastrojumo** [helm-unittest/helm-unittest#237]
The same test suites running in v0.3.6 prints a lot of messages like theses:

```sh
2023/11/07 13:38:25 trim copying "serviceAccount"
2023/11/07 13:38:25 trim copying "affinity"
2023/11/07 13:38:25 trim copying "nodeSelector"
2023/11/07 13:38:25 trim copying "externalSecrets"
2023/11/07 13:38:25 trim copying "apis"
2023/11/07 13:38:25 trim copying "externalSecrets"
2023/11/07 13:38:25 trim copying "image"
2023/11/07 13:38:25 trim copying "serviceAccount"
2023/11/07 13:38:25 trim copying "affinity"
 PASS  Test Ops CiliumNetworkPolicy     microservice/tests/ops_cnp_test.yaml
```
This behaviour is not present when running with v0.3.5. 
I found that message [here](https://github.com/helm/helm/blame/main/pkg/chartutil/dependencies.go#L341) that was introduced in helm `v3.13.1`, which I believe it was bumped in the go dependencies for v0.3.6 [here](https://github.com/helm-unittest/helm-unittest/compare/v0.3.5..v0.3.6#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R15).

**Comment by bjw-s** [comment]
I'm noticing this too, and it's quite annoying to try and filter through this in the unit test output. Hopefully this is something that can be fixed 👍
