### ISSUE TITLE
Cannot find subchart template files if filename includes chart name

### ISSUE THREAD

**Issue by jarrettprosser** [helm-unittest/helm-unittest#238]
I have a helm chart with nested subcharts. When I try to use snapshot assertions with `template` or `templates` to specify subchart files, I get the error: 
```
 FAIL  SubchartSnapshotWithTemplates    charts/subchart/tests/subchartSnapshotWithTemplates._test.yaml
        - subchart should create a resource (snapshot)

                - asserts[0] `matchSnapshot` fail
                        Error:
                                template "example-helm-unittest/charts/subchart/templates/subchart-object.yaml" not exists or not selected in test suite
```
This is similar to https://github.com/helm-unittest/helm-unittest/issues/219 but is only impacting subcharts. That is, if a resource template has the subchart name in the template filename, the template is not found. This does not occur when the resource is at the parent chart level. This is in 0.3.6.

To reproduce: 
- clone `helm-unittest`
- change directory to `test/data/v3/with-subchart`
- run `helm unittest -u .` and all tests will pass
- in `charts/child-charts/templates`, add `child-chart.yaml`:
```
apiVersion: example
kind: ChildChart
```
- in `charts/child-charts-tests`, add `child_chart_test.yaml`:
```
suite: child chart
templates:
  - templates/child-chart.yaml
tests:
  - it: child chart should create a resource 
    asserts:
      - matchSnapshot: {}
```
- run `helm unittest -u .` and the test will fail:
```
 FAIL  child chart      charts/child-chart/tests/child_chart_test.yaml
        - child chart should create a resource

                - asserts[0] `matchSnapshot` fail
                        Error:
                                template "with-subchart/charts/child-chart/templates/child-chart.yaml" not exists or not selected in test suite
```
- change the name of the template from `child-chart.yaml` to `fixed.yaml` (or any other change which removes the string `child-chart`), update the template path in the test, and the tests pass: 
```
 PASS  child chart       charts/child-chart/tests/child_chart_object_test.yaml
```

**Comment by mielmat** [comment]
that is also happening if you have templates (not a subchart) in path like templates/<directory name same as chart name>.

**Comment by snuggie12** [comment]
We too experienced an issue where the chart directory and the file name of the template match.

Based on some tests it appears to be some sort of match based principal. Our chart name/dir is `cluster` and `cluster2.yaml` and `containercluster.yaml` both fail. Changing it to `cc.yaml` works fine.

So yeah, it's not a "starts with" or "ends with" issue, but something like "contains".

**Comment by mielmat** [comment]
it is a bit embarrassing from my side, but I forgot to update plugin. Version 0.3.6 works as expected in my case (I used 0.3.5 before)
