### ISSUE TITLE
New docker image versions are not published

### ISSUE THREAD

**Issue by nburles** [helm-unittest/helm-unittest#244]
The latest published version is [3.11.2-0.3.0](https://hub.docker.com/layers/quintush/helm-unittest/3.11.2-0.3.0/images/sha256-6e1e699fc6001103f6419b389c4bca9b61076b11e89246443b33ee3127ad7678?context=explore) - would you possibly be able to publish a newer version, e.g. `0.3.6`? (I am particularly interested in the `set` at suite level feature in `0.3.4`)

**Comment by quintush** [comment]
Hello @nburles,

With the move the this main repo, the docker container also are moved.
You can find the latest version here:
https://hub.docker.com/r/helmunittest/helm-unittest

Greetings,
@quintush

**Comment by nburles** [comment]
Oh goodness, how did I miss that 🤦 

Thanks for pointing me in the right direction (and thanks so much for the tool!)
