### ISSUE TITLE
Regex issues

### ISSUE THREAD

**Issue by catalintgv** [helm-unittest/helm-unittest#245]
I`m using this regex:  \d+(?:Mi|Gi|M|G)\b\Z and also as alternative  \d+(?:Mi|Gi|M|G)\b(?!\s)  but unittest does not recognize \Z  and ?!
https://cheatography.com/davechild/cheat-sheets/regular-expressions/

 FAIL  Check the design service template        myprog/tests/design_test.yaml
        - Deployment check Memory and CPU of containers Image

                - asserts[0] `matchRegex` fail
                        Template:       myprog/templates/design.yaml
                        Error:
                                error parsing regexp: invalid escape sequence: `\Z`

 FAIL  Check the audit service template myprog/tests/audit_test.yaml
        - Deployment check Memory and CPU of containers Image

                - asserts[0] `matchRegex` fail
                        Template:       myprog/templates/audit.yaml
                        Error:
                                error parsing regexp: invalid or unsupported Perl syntax: `(?!`

**Comment by quintush** [comment]
Hello @catalintgv,

It is correct the unittest does not support \Z and ?! regex.
See the following site for the supported regex syntax https://github.com/google/re2/wiki/Syntax.

Greetings,
@quintush
