### ISSUE TITLE
How to test Lookup function Scenario with helm unittest

### ISSUE THREAD

**Issue by atulsingh0** [helm-unittest/helm-unittest#249]
I've stumbled upon this [closed issue - 108](https://github.com/helm-unittest/helm-unittest/issues/108) asked in year 2020 which refer to use older code base. Did we introduced the same functionality in this repo?  If so, can someone point me towards related documentation.

**Comment by wilmardo** [comment]
Interested in this too :)

**Comment by quintush** [comment]
Hello @atulsingh0, @wilmardo,

Please look at this [comment](https://github.com/helm-unittest/helm-unittest/issues/293#issuecomment-1948940579), it relates a lot to your situation.

Unless you are trying to lookup data which is not part of the helm chart, then a mock suggested as result, could solve the situation.

Greetings,
@quintush
