### ISSUE TITLE
bug: Repeated unwanted output "trim copying"

### ISSUE THREAD

**Issue by patrickstump** [helm-unittest/helm-unittest#260]
Found in version v0.3.6
Not occurring in v0.3.5

Operating Systems: Mac Sonoma 14.1.1 and Ubuntu 22.04
Occurs both in terminal (mac and linux) and when using a terminal inside of a microsoft vscode environment.

Helm Version:
```
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}
```

When running unittest the following output is repeated over and over again.

```code
2023/12/29 14:09:29 trim copying "headless"
2023/12/29 14:09:29 trim copying "annotations"
2023/12/29 14:09:29 trim copying "labels"
2023/12/29 14:09:29 trim copying "customStartupProbe"
2023/12/29 14:09:29 trim copying "nodeSelector"
2023/12/29 14:09:29 trim copying "global"
2023/12/29 14:09:29 trim copying "replicaSetConfigurationSettings"
2023/12/29 14:09:29 trim copying "configuration"
2023/12/29 14:09:29 trim copying "image"
2023/12/29 14:09:29 trim copying "containerPorts"
2023/12/29 14:09:29 trim copying "tls"
```

That is only a small sample.

I believe this has something to do with the default values file.
When I do NOT specify a values file or specify a path to a valid values file, these messages repeat over and over again.
When I put in an invalid path to a values file, the output does not occur.

Example where output occurs:

```yaml
suite: Test deployment
templates:
  - deployment.yaml
 ```

```yaml
suite: Test deployment
templates:
  - deployment.yaml
values:
  - values-required.yml
 ```
 
where values-required.yml is a valid file.

### Example where it does not occur

```yaml
```yaml
suite: Test deployment
templates:
  - deployment.yaml
values:
  - values-file-no-exist.yml
 ```
Output does not occur.

Downgrading to v0.3.5 seems to be my workaround.

**Comment by gionn** [comment]
already fixed on master - yet to release https://github.com/helm-unittest/helm-unittest/issues/237
