### ISSUE TITLE
isNull missing from json schema

### ISSUE THREAD

**Issue by gionn** [helm-unittest/helm-unittest#262]
the [json schema](https://github.com/helm-unittest/helm-unittest/blob/main/schema/helm-testsuite.json) is missing `isNull` property

<img width="603" alt="Screenshot 2024-01-02 at 17 26 57" src="https://github.com/helm-unittest/helm-unittest/assets/71768/2991beea-594d-46c6-8e36-a59f9da05fb8">

**Comment by quintush** [comment]
Hello @gionn,

It is correct isNull is not part of the json schema.
The isNull deprecated and is replaced by notExists, exists (when you want to check if the path is actual available) or isNullOrEmpty, isNotNullOrEmpty (when you want to check if the value of a path is null or empty.

As some time (probably in version 0.5.0) the isNull and isEmpty will be removed. 

Greetings,
@quintush

**Comment by gionn** [comment]
Thanks for clarifying, I've raised a PR to clearly state that in the docs I check everytime I am writing unit tests :D
