### ISSUE TITLE
ContainsDocument assertion fails on multi document templates

### ISSUE THREAD

**Issue by peter-mcclonski** [helm-unittest/helm-unittest#268]
After updating to 0.4.0, we have encountered issues with ContainsDocument failing in multi document templates.  The example shown in #205 remains representative of the failure (with or without `any: true`).  Notably, removing the second document allows the test to pass.

**Comment by ThomasEhling** [comment]
Additional information: we noticed that only the very last file passed in contains document.

In a yaml with 3 role binding object, only the last one is detected. The other two will failed consistently. The pattern does repeat is we change the object position within the file: only the last is detected.

The argument any=true does not affect this bug.
