### ISSUE TITLE
Feature: filter by kind and metadata (or any content in a manifest file) when selecting templates to test

### ISSUE THREAD

**Issue by alexandreribeiro** [helm-unittest/helm-unittest#285]
Instead of starting tests like this:

suite: Integration Test - Networking
templates:
- "service/load-balancer-service.yaml"
tests:
- it:
[....]

I would like to start tests like this:

suite: Integration Test - Networking
templates:
- filter:
  path: kind
  value: Service
- filter:
  path: spec.type
  value: LoadBalancer

**Comment by quintush** [comment]
Hello @alexandreribeiro,

This feature is available with the documentSelector option.
See following test as example: https://github.com/helm-unittest/helm-unittest/blob/main/test/data/v3/with-document-select/tests/foo_rbac_test.yaml

Greetings,
@quintush
