### ISSUE TITLE
$.Template.BasePath can't be handled properly

### ISSUE THREAD

**Issue by cyfu** [helm-unittest/helm-unittest#293]
I added following annotation in `helm-unittest/test/data/v3/with-subchart/charts/child-chart/templates/deployment.yaml`. 
```yaml
annotations:
  checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
And also created the `configmap.yaml` file in the `child-chart/templates` folder.

`helm template` command works well, but `helm unittest .` produces error:
```
Error: template: with-subchart/charts/child-chart/templates/deployment.yaml:12:24: executing "with-subchart/charts/child-chart/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: no template "with-subchart/charts/child-chart/templates/configmap.yaml" associated with template "gotpl"
```
Attached is the modified `with-subchart` and console output.
[with-subchart2.zip](https://github.com/helm-unittest/helm-unittest/files/14155621/with-subchart2.zip)
[console_output.txt](https://github.com/helm-unittest/helm-unittest/files/14155622/console_output.txt)

**Comment by instriker** [comment]
Same issue. 

What we are doing in our case is including a sub-chart template to do some dynamic adjustements. This was working with unit test 0.2.8, but stopped working when upgrading to 0.4.1:

```
{{- $filePath := ( print $.Template.BasePath "../charts/testkube/charts/testkube-api/templates/minio.yaml" ) }}
{{- $filePath = $filePath | replace "templates/../" ""}}
{{- $manifest := include "filePath" $someContext }}
```

**Comment by quintush** [comment]
Hello @cyfu, @instriker,

Please take a look at the [deployment test](https://github.com/helm-unittest/helm-unittest/blob/main/test%2Fdata%2Fv3%2Fbasic%2Ftests%2Fdeployment_test.yaml) in the basic sample project.

To run the tpl functions the helmchart expects that the linked yaml files are part of the helmcht 
To isolated the unit tests, the template filter only loads the required files. So to have a valid deployment test with a validation of the configmap hash, it is important to also include the configmap.yaml as part of the templates filter.

Greetings,
@quintush

**Comment by instriker** [comment]
Yes it works, thank you! 

I didn't figure the best way to handle the templates to reference files inside a chart.yaml, but found *.yaml  to be working as in this config:

```
templates:
- "*.yaml"
tests:
- it: my test
  template: templates/deployment.yaml
  asserts: 
  # ...
```

**Comment by cyfu** [comment]
Thanks @quintush , it works for me.
