### ISSUE TITLE
Update Helm

### ISSUE THREAD

**Issue by Ornias1993** [helm-unittest/helm-unittest#295]
Latest helm version has some super important (10x) speed improvements for rendering.
Please update to latest version of helm.

**Comment by stavros-k** [comment]
More info why this is needed.
https://github.com/helm-unittest/helm-unittest/pull/277#issuecomment-1902630682

I should add that its 1200 tests that pass with this, which should give good indicators that it shouldn't break anything

**Comment by Ornias1993** [comment]
@stavros-k With this not getting much attention at all and even code being merged that fails its own test, forking might become an option.
