### ISSUE TITLE
Ability to use multiple documentSelectors

### ISSUE THREAD

**Issue by raxod502-plaid** [helm-unittest/helm-unittest#302]
The `documentSelector` feature is only useful for some specialized use cases in its current form, because it only supports a single selector. As discussed in https://github.com/helm-unittest/helm-unittest/pull/208#issuecomment-1763994399 and https://github.com/helm-unittest/helm-unittest/pull/208#issuecomment-1964943356, it should be possible to select a manifest _at least_ by a combination of name and kind.

**Comment by quintush** [comment]
Hello @raxod502-plaid,

The documentSelector setup is much more powerfull than the basic examples show.

The path has Yaml JsonPath support, making it possible to filter within the whole document to select a specific part of the document. See the [rbac example](https://github.com/helm-unittest/helm-unittest/blob/main/test/data/v3/with-document-select/tests/foo_rbac_test.yaml) in the documentSelector chart.

The value is an object so it is possible to validate a complete yaml object. See the [top level example](https://github.com/helm-unittest/helm-unittest/blob/main/test/data/v3/with-document-select/tests/top_level_test.yaml) in the documentSelector chart.

Greetings,
@quintush

**Comment by raxod502-plaid** [comment]
Awesome, thank you! That resolves my concern.
