### ISSUE TITLE
Add support for linux/arm64 docker image

### ISSUE THREAD

**Issue by ChenYi015** [helm-unittest/helm-unittest#321]
Currently, the docker image only supports linux/amd64 platform, it would be better to add support for linux/arm64 platform.

**Comment by quintush** [comment]
Hello @ChenYi015,

Thanks for the feedback.
I will check on publishing multiple platform specific docker containers.

Greetings,
@quintush

**Comment by ivankatliarchuk** [comment]
Any plans to use a GitHub action for that? With github action we can add vulnerability scanning and etc.
