### ISSUE TITLE
missing docker image for `v0.5.1`

### ISSUE THREAD

**Issue by sebradloff** [helm-unittest/helm-unittest#348]
It appears there's no docker image for `v0.5.1` in the `helmunittest/helm-unittest` docker repository. https://hub.docker.com/r/helmunittest/helm-unittest/tags/?page=&page_size=&ordering=&name=

The current "latest" tag has the same digest as `v0.5.0`.
![Cursor_and_helmunittest_helm-unittest_Tags___Docker_Hub](https://github.com/helm-unittest/helm-unittest/assets/7495006/371a765d-ff69-4c61-a816-013da619f0c7)

**Comment by ivankatliarchuk** [comment]
Hi @quintush , any plan to create a 0.5.1 docker image? Thanks

**Comment by Xitric** [comment]
Seems to be added now: `3.15.2-0.5.1`

**Comment by Agger1995** [comment]
It appears that `3.15.2-0.5.1` has been delisted from the docker registry, and no other image with plugin version `0.5.1` is available.
@quintush any update regarding this?

**Comment by quintush** [comment]
Hello @Agger1995,

The images are back.
I accidently removed the images when I was testing multi-arch containers.
Sorry for the inconvenience.

Greetings,
@quintush

**Comment by ivankatliarchuk** [comment]
Resolved. Worth to close
![Screenshot 2024-08-17 at 10 53 05](https://github.com/user-attachments/assets/f0191962-fe5d-4ea9-b638-81de1eaf38c8)
