### ISSUE TITLE
Feature: Allow to use matchRegex with failedTemplate errorMessage

### ISSUE THREAD

**Issue by jdiegosierra** [helm-unittest/helm-unittest#349]
asserts:
      - failedTemplate:
          matchRegexErrorMessage: \berror\b

**Comment by ivankatliarchuk** [comment]
https://github.com/helm-unittest/helm-unittest/blob/6f3a6f717b8b3baf403ecc41384e13c1ea4fdb25/pkg/unittest/validators/failed_template_validator.go#L17

**Comment by jdiegosierra** [comment]
@ivankatliarchuk thank you!
