### ISSUE TITLE
Assertion does not match when using `camelcase`  function in helm-unittest `v0.5.2`

### ISSUE THREAD

**Issue by AlbertoOS** [helm-unittest/helm-unittest#359]
# Issue

In version `v0.5.2` assertions expecting a result in camelcase fails when input data is in lowercase, this problem is not seen in version `v0.5.1`.

## Steps to Reproduce

First, outputing helm version:

```bash
helm version
```

> version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}

Then we create a new example chart and we modify the `_helpers.tpl` file to camelcase the `fullnameOverride` variable:

```bash
helm create example-chart

sed -i 's/{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}/{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" | camelcase }}/g' example-chart/templates/_helpers.tpl
```

After this, we add a test for the deployment template:

```bash
mkdir example-chart/tests

cat << EoF >  example-chart/tests/deployment_test.yaml
suite: test camelcase in deployment
templates:
  - deployment.yaml
tests:
  - it: should be camelcase
    set:
      fullnameOverride: test
    asserts:
      - equal:
          path: metadata.name
          value: Test
EoF
```

Now we install helm-unittest plugin in version `v0.5.1` and run the test:

`helm plugin uninstall unittest || : && helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v0.5.1 && helm unittest example-chart`

`v0.5.1` unittest output:

```bash
### Chart [ example-chart ] example-chart

 PASS  test camelcase in deployment example-chart/tests/deployment_test.yaml

Charts:      1 passed, 1 total
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        1.974677ms
```

Finally we install helm-unittest plugin in version `v0.5.2` and run the same test again:

`helm plugin uninstall unittest || : && helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v0.5.2 && helm unittest example-chart`

`v0.5.2` unittest output:

```bash
### Chart [ example-chart ] example-chart

 FAIL  test camelcase in deployment example-chart/tests/deployment_test.yaml
    - should be camelcase

        - asserts[0] `equal` fail
            Template:   example-chart/templates/deployment.yaml
            DocumentIndex:  0
            Path:   metadata.name
            Expected to equal:
                Test
            Actual:
                test
            Diff:
                --- Expected
                +++ Actual
                @@ -1,2 +1,2 @@
                -Test
                +test


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        1.858943ms

Error: plugin "unittest" exited with error
```

**Comment by ivankatliarchuk** [comment]
What the expected behaviour is in your opinion? Looks like 0.5.2 has some undocumented fix

**Comment by AlbertoOS** [comment]
I think the expected behaviour should be like version 0.5.1 

That is mainly because I'm using `camelcase` function in my templates and Helm renders them correctly with camelcase ("Test" in the example). So the unittest behaviour should be consistent with Helm's behaviour.

**Comment by ivankatliarchuk** [comment]
I have no time to validate yer But worth to double check the behaviour of the camelcase function. If test became a Test is not a camelCase but a PascalCase. Looks like helm version or sprig dependency was bumped where the fix is.

**Comment by AlbertoOS** [comment]
Oh, I see now what you meant by undocumented fix. Helm and unittest were treating camelCase as PascalCase.

However looking into [sprig string functions](https://masterminds.github.io/sprig/strings.html), it does seem to be the intended behaviour.
There is no documented PascalCase and camelCase is treated as CamelCase:

> camelcase
> Convert string from snake_case to CamelCase
> `camelcase "http_server"`
> This above will produce HttpServer.

---

Looking further into this, I've found a question regarding camelcase behaviour in [sprig repo](https://github.com/Masterminds/sprig/issues/328), the fix should only exist in [sprout (sprig fork)](https://github.com/go-sprout/sprout), and from what I've checked, both helm-unittest and helm still use sprig.

**Comment by ivankatliarchuk** [comment]
Ok found out why the behavior differs in never version. The fix exists in dependency ﻿https://github.com/huandu/xstrings which is an indirect dependency to sprig and helm


<img width="1223" alt="Screenshot 2024-08-10 at 15 55 12" src="https://github.com/user-attachments/assets/a151d8be-b84b-4b75-853d-ff8fde7c42f7">
<img width="1223" alt="Screenshot 2024-08-10 at 16 15 47" src="https://github.com/user-attachments/assets/01ac1201-9c3f-4898-b4f1-f184a01c35d1">

**Comment by ivankatliarchuk** [comment]
Agree it's a bug. As there is a version mistmatch in between Helm and Helm unittest
<img width="1265" alt="Screenshot 2024-08-10 at 16 18 28" src="https://github.com/user-attachments/assets/062d9ecb-00f0-4ba2-b2db-2d510fb34c25">

**Comment by ivankatliarchuk** [comment]
The helm-unit test's release cycle is unpredictable and lacks a fixed schedule. If you encounter issues, you're welcome to submit a pull request that reverts to a previous version with integration tests. Meanwhile, I'll attempt to create a merge request in the Helm repository to update an indirect dependency version.

**Comment by quintush** [comment]
Hello @AlbertoOS, @ivankatliarchuk,

Thanks for the feedback and the additional investigations.
Based on the comments by the helmteam, it's best to rollback the version to keep the behaviour the same as helm.

Greetings,
@quintush

**Comment by ivankatliarchuk** [comment]
Worth to write a unit and end-2-end test of this.

Dependency is update
- sprig https://github.com/Masterminds/sprig/blob/e708470d529a10ac1a3f02ab6fdd339b65958372/go.mod#L10
- helm https://github.com/helm/helm/blob/3a3e3846ca9c929a6966583b461181e70f19bc13/go.mod#L9C2-L9C33
