### ISSUE TITLE
Regression: Rendering with subchart alias with version override not in snapshot in v0.6.3 (succeeds in v.0.6.2)

### ISSUE THREAD

**Issue by sgerke-1L** [helm-unittest/helm-unittest#457]
**Describe the bug**
Rendering a chart with subchart alias and chart version override omits the alias in v0.6.3 from the snapshot

**To Reproduce**
I've added a test case here:
https://github.com/sgerke-1L/helm-unittest/tree/bug-rendering-with-subchart-alias

Shows the snapshot in v0.6.3 where the aliased subchart (another-postgresql) is missing:
https://github.com/helm-unittest/helm-unittest/commit/6563aa0bd7d10b46eff6353377148fd478739f12

Shows the snapshot in v0.6.2 where the aliased subchart (another-postgresql) is present:
https://github.com/helm-unittest/helm-unittest/commit/a3c13779f6e50b71aeffa5d6a37b9466abc7be52

**Comment by ivankatliarchuk** [comment]
Thanks for submitting an issue. We had no coverage for this case, happens ;-)

**Comment by sgerke-1L** [comment]
Thanks for fixing it so quickly. Is there a release planned so we can integrate the fix downstream?
