### ISSUE TITLE
greaterOrEqual seems to mix up test value with expectation

### ISSUE THREAD

**Issue by chlab** [helm-unittest/helm-unittest#515]
**Describe the bug**
When using a `greaterOrEqual` assertion, like so:

```
asserts:
      - greaterOrEqual:
          path: spec.minAvailable
          value: 1
```

One would expect a path of `spec.minAvailable` of a given template to be valid if it's value is greater than or equal to 1. However, the test fails if `spec.minAvailable` is e.g. set to 2, resulting in the error:

```
Expected to be greater then or equal to, got:
				the expected '1' is not greater or equal to the actual '2'
```

It seems to me that the comparison is the wrong way around and it's testing the value provided in the test file as the expectation.

**To Reproduce**
* clone [this repo](https://github.com/chlab/helmunittest-greaterorequal)
* run helm unittest . -f tests/test-pdb.yaml

**Expected behavior**
The value provided in the test file is the value the expected path in the template is compared against. The teststuite in the reproduction repo linked above should pass.

**Screenshots**
See the reproduction [repo](https://github.com/chlab/helmunittest-greaterorequal) Readme

**Desktop (please complete the following information):**
 - OS: Mac Sequioa 15.1.1
 - Plugin Version 0.7.0

**Additional context**

**Comment by ivankatliarchuk** [comment]
Hi. From the https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#assertion-types
```
Assert the value of specified path is greater or equal to the value.
```

**Comment by quintush** [comment]
Hello @chlab 

Thanks for the feedback, and you are right.
The comparison is reversed.

Completely missed this part and will fix it asap.

Greetings,
@quintush

**Comment by chlab** [comment]
Great news, thanks for the quick fix @quintush!
